### ISSUE TITLE
spring.thymeleaf.mode=LEGACYHTML5 not working

### ISSUE THREAD

**Issue by coolcooldool** [gdiasdasilva/hotel-booking#2]
Hello,

When I open homepage, I get an error in my log:

`org.xml.sax.SAXParseException: The element type "input" must be terminated by the matching end-tag "</input>".
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) [xercesImpl-2.11.0.jar!/:na]
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source) [xercesImpl-2.11.0.jar!/:na]`

I think it casue of spring.thymeleaf.mode didn't work.
But I searched all of Google, It seems the config is right. I don't know why?
Tomcat version or JDK version is wrong? 

Thanks!

**Comment by coolcooldool** [comment]
I answer it myself.

I used 6 hours to find why the `spring.thymeleaf.mode=LEGACYHTML5` didn't work.
Finally, I figured it out, problem is:
`application.properties` file location!

When I download source code the file in `/ciai-lab2/src/main/java/`
The problem is maven do not copy this file to created jar file,
so this setting will not work.

**Comment by gdiasdasilva** [comment]
I'm glad you found the solution!
